# SWOT Analyse

Onderstaande info is tot stand gekomen via een gesprek met Geert Sioen.

## Sterktes

Het is een internationaal gedragen meetnet met een overkoepelende organisatie (ICP-Forests) die de kapstok vormt voor het meetnet. De monitoring wordt begeleid door verschillende expertengroepen van het internationale netwerk rond bossen.

De ingezamelde data van de vele landen heeft geleid tot heel wat publicaties, wat wijst op de wetenschappelijke waarde van dit werk.

Daarnaast is het al een heel langlopend meetnet, dit gaat reeds over 35 jaar in Vlaanderen en bijna 40 jaar in Duitsland, dus dit is een heel waardevolle tijdsreeks.


Er zijn veel Europese landen die deelnemen, dus het meetnet is wijdverspreid in Europa.

Doordat dezelfde proefvlakken telkens opnieuw bezocht worden, is dit heel informatief voor de evolutie in de tijd.

Het is gegroeid uit een Europese verordening. Ondanks dat enkele verplichtingen zijn weggevallen nemen nog steeds veel landen deel aan dit netwerk van meetnetten.

Het protocol is afgeklopt tussen de verschillende landen en er is een handleiding ter beschikking via ICP forests. Dit protocol wordt ook gevolgd door de meeste landen.

De hoofdmeetpunten zijn geselecteerd op basis van objectieve criteria, namelijk een systematisch raster van 16x16km met mogelijkheid tot verdichtingen voor de deelnemende landen.


## Zwaktes

Hoewel er jaarlijks gemeten wordt, is het meetnet niet voldoende als early-warning systeem. Wanneer een nieuwe ziekte of infectie optreedt, kan niet gegarandeerd worden dat dit meetnet dit kan opmerken.

Er wordt enkel basisinformatie verzameld, namelijk kroonbeoordeling en symptoombeschrijving, dus er is geen link met andere invloedsfactoren zoals bodem, klimatologische variabelen, ziektes en andere abiotische invloeden. Enkel voor de 5 locaties die ook in het level-2 meetnet opgenomen zijn is deze informatie ter beschikking

Dit is ook een zwakte in Europese context, ook al de Europese meetpunten zijn enkel op een beperkt aantal locaties in detail bekeken.

Het meetnet is niet volledig representatief voor Vlaanderen, omdat gekozen is in 1995 om enkele soorten te bevoordelen bij de selectie van nieuwe proefvlakpunten. Dit wil niet zeggen dat het meetnet daarvoor veel in waarde mindert, maar dit is wel iets om in het achterhoofd te houden.

Verder wordt niet alle bosvormen vertegenwoordigd in de proefvlakken, omdat punten weggehouden worden van de bosrand, en meetpunten niet gelegd kunnen worden in heel kleine clusters van bomen.

Doordat de tijdreeks al heel lang loopt en door de keuze van de bomen in ieder proefvlak, begint de veroudering van de bomen een belangrijkere rol te spelen in de evolutie van de vitaliteit, waardoor een verslechterende trend het gevolg kan zijn van de leeftijd van deze specifieke bomen, dan de algemene gezondheidstoestand in Vlaanderen.


## Opportuniteiten

Zonder veel extra budget zijn niet heel veel extra mogelijkheden voor het meetnet voorhanden.

In sommige landen gebeuren ook nog bladanalyses binnen de meetnetproefvlakken, om een beter zicht te krijgen op de vitaliteit, iets wat in Vlaandern nog nooit gebeurd is. Daarnaast zouden ook leefijdsbepalingen van de bomen, vegetatie-opnames in de proefvlakken interessante informatie kunnen opleveren.

In Vlaanderen zijn redelijk veel andere metingen voorhanden, dus misschien kan de trend beter verklaard worden door een statistisch model, zonder veel extra kostprijs, dan puur uit te gaan van een constante trend zoals in een standaardmeetnet. 

Vroeger (2003) zijn er eens bodemanalyses gebeurd in alle proefvlakken, maar dat is nooit meer herhaald, terwijl er intussen op het INBO heel veel bodemonderzoek gebeurt. Op zich is er wel interesse in het MILKLIM team om de bosinventarisatieproefvlakken eens opnieuw te bezoeken voor bodemanalyses.

Voorlopig worden gegevens niet meer in Fieldmap ingegeven (dateert van 2010) en dus staan de nieuwe plots hier nog niet in. Als alles ook in Fieldmap toegevoegd wordt waaronder ook de dendrometrische gegevens voor het hele proefvlak, biedt dat perspectieven naar links tussen vitaliteit en beheervormen, afstand tussen bomen, ... . Daarnaast is het ook gemakkelijk dat alle bomen via Fieldmap gemakkelijk teruggevonden kunnen worden.

## Bedreigingen

Het huidige meetnet wordt door een heel beperkte kern van gekwalificeerde personeelsleden uitgevoerd, daarnaast zijn 3 van de 4 intussen de leeftijd van 60 gepasseerd en komen die dicht bij hun pensioen.

Om het meetnet in de toekomst te kunnen blijven opvolgen zal op korte termijn training moeten voorzien worden voor enkele nieuwe experten, omdat de kroonbeoordeling wel iets is, waarvoor training en ervaring nodig is, om dit goed te doen.

Het laatste jaar is alles van het meetnet van veldwerk tot data-invoer tot rapportage door 1 persoon gebeurd, wat niet voordelig is voor de kennis hieromtrent bij andere collega's.

De monitoring is niet de duurste van het INBO maar er moet wel voldoende budget zijn.

