# Aanbevelingen

## Kostprijs meetnet


### Algemene kostprijs

Het meetnet is niet heel duur omdat de veldwerk inzet beperkt is in de huidige situatie tot ongeveer 40 mensdagen veldwerk, aangevuld met XX dagen gegevensinvoer en kwaliteitsbewaking en XX dagen voor de rapportage.

Er moet tijd voorzien worden voor het trainen van personeel om dit meetnet te kunnen verderzetten.

Deels overlappend met dit meetnet emn met dezelfde methodologie wordt ook de essenziekte onderzocht, maar het plan is dit heel binnenkort stop te zetten omdat XXX

### Welke uitspraken kunnen gedaan worden

Het meetnet is gemaakt om een uitspraak te doen over heel Vlaanderen over alle boomsoorten heen (dat kan met XXX precisie met YYY meetpunten). Om een uitspraak per boomsoort te doen met betrouwbaarheid XXX, moet het meetnet uitgebreid worden met YYY.


## Technische verbeteringen voor de toekomst

### Representatitivteit

Om een goede uitspraak over Vlaanderen te doen, moeten we een goed zicht krijgen voer hoe onze steekproef afwijkt (door stratificatie om sommige soorten meer mee te hebben) van de doelpopulatie in Vlaanderen. Hiervoor kan bijvoorbeeld de bosinventarisatie gebruikt worden.

### Verouderende proefvlakken

Doordat het verouderen van de bomen zelf een steeds belangrijkere factor wordt in de evolutie van het bladverlies zelf, dekt dit meetnet niet meer volledig de doelstelling, daarom moet een goede vervangingstrategie worden uitgewerkt over hoelang proefvlakken in de dataset blijven en hoe die vervangen moeten worden, zodat de bosvitaliteit representatief blijft voor de gezondheidstoestand van de bomen in Vlaanderen

### Trend over heel lange tijdreeks

Om de uitspraak zoals een gewoon meetnet te kunnen doen van een evolutie van 12% over 12 jaar wordt het meetnet eigenlijk een te lange tijdreeks met heel veel systematische subtrends en is het beter te focussen op de laatste X jaar in plaats van de hele tijdreeks te nemen voor de trend.