
# Situering huidige situatie in relatie tot de ontwerpfases in een meetnet

## Historiek

Het bosvitaliteitsmeetnet, of Level-I meetnet, is een heel langlopend meetnet opgestart in 1987. Dit is tot stand gekomen via het expertenpanelgroep ICP-forests, met vertegenwoordigers uit heel Europa.

Dit meetnet is ge-evolueerd in de loop van de jaren en er is ook al eens een revisie gebeurd enkele jaren geleden << concretiseren >> onder leiding van Paul Quataert << referentie >>


## Vage informatiebehoefte:

## Fase 1: Vraag- en aanbodsanalyse

### Welke vraag moet beantwoord worden?

Hoe evolueert de gezondheidstoestand van de bomen in de Vlaamse bossen?

### Wie is de eindgebruiker van de resultaten?

- Er is een duidelijk rapport dat voor alle stakeholders raadpleegbaar is
- Er is geen policy rond de openheid en FAIR-ness van de data
- <<wie is de doelgroep>>


### Doelstelling en Normstelling

- Er ontbreken duidelijke criteria van welke evolutie op welke periode door het meetnet gedetecteerd moet worden
- Hierbij zullen we een keuze moeten maken << KEUZE >>

### Doelpopulatie

De doelpopulatie is << AANVULLEN >>
    
- De steekproef bevat enkel punten volledig in bos
- Heel jonge bestanden komen niet in aanmerking
- Enkel gesampled in gebieden met oudere bomen
- Het meetnet is geconcipieerd om een uitspraak op niveau Vlaanderen te doen
    - Voor een analyse per boomsoort is dit nog niet uitgerekend
    

## Fase 2: Ontwerp gegevensinzameling


### Meetvariabele


#### Omschrijving

- Het bladverlies in een boomkroon vormt de responsvariabele
- Dit wordt visueel beoordeeld door getraind personeel en volgens Europese aanbevelingen binnen ICP Forests
- De kroontoestand wordt in klassen van 5% beoordeeld
- Een boom wordt als beschadigd beschouwd vanaf er meer dan 25% blad- of naaldverlies is

#### Beperkingen

- Een correcte objectieve visuele beoordeling in klassen van 5% is niet mogelijk
    - Er is wel duidelijk onderscheid te maken in klassen van ongeveer 20%
    - Door meerdere bomen binnen een proefvlak te beoordelen, kan je wel de precisie over het proefvlak grondig verhogen, wat pleit voor genoeg beoordeelde bomen per proefvlak
    
<< FIGUUR MAKEN DIE DIT ILLUSTREERT >>

### Statistische eenheid

De statistische eenbeid is een proefvlak. De verschillende bomen binnen een proefvlak zorgen voor een nauwkeurigere bepaling van of van de beschadigingsgraad binnen een proefvlak

### Keuze van plots

Het meetnet kan niet gezien worden als een gebiedsdekkend of als volledig representatief voor Vlaanderen, omdat er enkele keuzes gemaakt zijn:

- De basis van het meetnet is een 16x16km (later 8x8km) grid
    - Met het grootste grid hebben we slechts 9 ICP-forests punten
    - Hiervoor zijn er regionale proefvlakken bijgekomen <<hoeveel, een 30 tal?>>
    - Dit ging in de eerste fase over <<xx>> proefvlakken waarvan <<yy>> Level-II proefvlakken voor uitgebreide monitoring
- Dit werd selectief uitgebreid naar een 4x4km grid in 1995
    - <<criteria?>>
    - Proefvlakken met minder gerepresenteerde boomsoorten krijgen de voorkeur
        - Hier gaat het vooral over beuk
    - Het aantal proefvlakken steeg naar 72
    - Het aantal Level-II proefvlakken beperkt tot 5
- Proefvlakken verdwijnen door kappingen, herbestemmingen, schade, te weinig resterende bomen, ...
    - Sedert 2019 jaarlijkse uitbreiding van 2 a 3 proefvlakken per jaar
    - Nieuw proefvlak ligt op minstens 4km van een ander proefvlak
- Omgaan met proefvlakken aan de rand van een bos
    - Proefvlak wordt verlegd zodat het volledig in bos valt
    - Er wordt zoveel mogelijk geprobeerd dit binnen hetzelfde bos te doen
- Vergelijking met andere Europese landen:
    - Grote landen beperkten zich tot het 16x16km grid
    - Kleinere landen gaan denser
    - Op Zweden na worden ook in andere Europese landen de metingen op dezelfe locatie herhaald
    - Vorm van proefvlak en hoe bomen erbinnen geselecteerd worden varieert van land tot land
    - Er is wel een manual van ICP-Forests waar alle landen zich op moeten baseren, maar waar deze kleine variaties toegelaten worden

### Keuze van bomen binnen een plot

- Oorspronkelijk (voor 2012):
    - Vanuit het gekozen gridpunt worden 4 clusters, 1 per windrichting, van 6 bomen gekozen binnen een <<bepaalde>> afstand van het gridpunt
- Later
    - Gekozen voor meer synergie met de Vlaamse bosinventarisatie (VBI)
    - Steekproefcirkels met een straal van 18 meter
        - Gevolg: vaak minder overgebleven bomen in een plot
    - Alle bomen met een diameter > 7cm worden opgenomen
    - De bomen moeten codominant zijn
        - de kroon moet aan het licht kunnen
        - mag niet gedomineerd worden door een nabije boom

### Vervangen van bomen en plots

- <<nog aan te vullen>>


### Kostprijs

De kostprijs is in 2022 gedetailleerd genoteerd

- Aankomstuur en vertrekuur op het proefvlak
- Rij-afstanden
    - Al het verwerk is met dezelfde wagen (Duster 1XRY100) uitgevoerd
    - In 2022 ging dit over 800 a 9000 km
- Mandagen
    - in 2022 ging dit over 38 mandagen, gepresteerd door onderzoeker niveau A

### Veldwerk

- Rij-afstanden naar de verschillende proefvlakken nemen het meeste tijd in beslag
- Over het algemeen kunnen 2 a 3 profvlakken per dag bezocht worden
- Tijdens het bezoek gaat de grootste tijd naar de kroonbeoordeling, andere meetvariabelen worden (zoals schadesymptomen) worden terloops genoteerd


## Fase III: Ontwerp databeheer en analyse

### Analyse en rapportage


- << TIJDSBESTEDING??>>
    - Geert?
    - Pieter: enkele dagen per jaar voor de scripts te maintainen en uit te breiden

### Data-opslag

- Er is nog geen data management plan voor deze data
- De data wordt bewaard in een door het team databeheer beheerde databank D0004_Bosvitaliteit
- De data wordt ook in een datawarehouse intern ter  beschikking gesteld
- Deze data is enkel intern beschikbaar


## Fase 4: Ontwerp rapportering en communicatie

- Het hoofdrapport is een jaarlijks INBO-rapport
    - Beschrijft de proefvlakken in detail
    - Via R scripts wordt een beperkte analyse gedaan rond de trend
- Jaarlijks wordt ook gerapporteerd naar ICP forests
- Er is een natuurindicator "beschadigde bosbomen" die dit meetnet gebruikt
- Verder nog publicaties naar de Vlaamse statistieken, INBO-nieuwsbrief, ...

## Fase 5: Implementatie

Dit is een lopend meetnet en is dus reeds geïmplementeerd


# Wat kan met het huidige meetnet aangetoond worden

## Analyse over Vlaanderen over alle soorten heen

### Detecteerbaar verschil tussen 2 opeenvolgende jaren

### Detecteerbaar verschil over een periode van 12 jaar

### Detecteerbaar verschil over een rollende periode van 12 jaar

## Analyse per boomsoort


# Kostenefficiëntie

## Evolutie proefvlakken

<!---

## Steekproef

eenheid is plot met meerdere boommetingen voor uitfilteren beoordelingsfout

## Veldwerk

Hoelang duurt alles, tijdsinvestering, hoelang bladerdek opmeten, hoelang alle andere metingen

## Analyses

Mann-Kenly Sen-slope: verder uitvlooien en manueel berekenen om power analyse te kunnen doen!
Eventueel maueel, per boom een statistiek uitvlooien en die dan uitrekenen met als random effect plot en soort, alsook de analyse voor soort apart.

# SWOT analyse huidig meetnet

Onderstaande info is tot stand gekomen via een gesprek met Geert Sioen.

## Sterktes

- Internationaal gedragen meetnet 
    - ICP-Forests is de internationale orgqnisqtie die de kapstok vormt voor het meetnet
    - Monitoring begeleid door verschillende experntengroepen van het internationaal netwerk
- Publicaties op internationale schaal die gebruik maakt van de data uit verschillende Europese partnerlanden
    - <<aan te vullen: voorbeelden>>
- Heel langlopend meetnet
    - ICP-Forests in 1985 opgericht
    - Kroonbeoordelingen vanaf 1986 gestroomlijnd over de verschillende landen
    - Vlaanderen neemt deel sedert 1987
- Vastgelegd protocol
    - Hoofdzakelijk hetzelfde meetprotocol wordt gebruikt over de verschillende landen
- Vastgelegde meetpuntenselectie
    - Objectief geselecteerd via een systematisch raster

## Zwaktes

- Kan niet gebruikt worden als early warning system
    - Nieuwe ziektes of infecties worden niet onmiddellijk opgemerkt
- Enkel basisinformatie over de algemene gezondheidstoestand
    - Meer uitgebreid meetnet voor fundamenteel onderzoek: Level-II  meetnet
    - Deze detailplots komen niet zoveel voor (slechts 5 in Vlaanderen)
- Het meetnet is niet representatief voor Vlaanderen
    - selectieve uitbreiding voor onderbemonsterde soorten
- Door met dezelfde proefvlakken te werken veroudert de gerepresenteerde populatie
    - veroudering kan ook een invloed hebben op de vitaliteit

## Opportuniteiten

- Binnen de huidige budgettering niet veel extra mogelijk
    - Meetnet kan misschien geschikt zijn voor een masterthesis
- Voorlopig heel beschrijvend meetnet
    - De trend zou statistisch gelinkt kunnen worden aan klimaatvariabelen
        - Dit is enkele jaren geleden eens gedaan
        - Periodiek herhalen
        - Weinig extra kosten: aankoop klimaatgegevens + tijd voor statische analyse



## Bedreigingen

- Het huidige meetnet wordt door een heel beperkte kern uitgevoerd
    - 3 op 4 kroonbeoordelingsexperten naderen hun pensioen
    - training vereist om de beoordeling juist te kunnen uitvoeren

- Wat zijn volgens jou de zwaktes van het meetnet?
- Waarin zou het meetnet verbeterd kunnen worden?
- Zou er meer uit het meetnet gehaald kunnen worden?
- Zijn er problemen te verwachten in de toekomst voor het meetnet?

## Extra interessante wensen

Extra analyses hebben altijd een extra kostenplaatje, maar enkele mogelijkheden zouden kunnen zijn:

- Bladanalyses binnen het meetnet
    - bij ons nooit gedaan, terwijl dit wel in andere landen gebeurt
- Regelmatig een begeleidend bodemonderzoek uitvoeren
    - Nu is dit enkel eens in 2003-2004 gebeurd
- Metingen kunnen uitgebreid worden
    - leeftijdsbepalingen
    - vegetatieopnames


# Vraaganalyse meetnet

## Input gevraagd aan Geert

### Swot-analyse



### Historiek

Er zijn verschillende versies geweest van het meenet.

- Hoe zijn de huidige proefvlakken geselecteerd (ik kan dat zelf nalezen, maar misschien gemakkelijker als je dat vertelt
- Worden proefvlakken verschoven
- Zijn de proefvlakken representatief voor alle bossen, voor bomen midden in bossen, voor oude bomen, ...?
- In hoeverre is er nog een Europese verplichting?

### Vroegere analyses

- We hebben ooit eens een verklarend model gemaakt voor dit meetnet, is dit iets dat we periodiek herhalen?

### Kosten

De kern van het meetnet is het bladverlies, maar er worden ook heel veel andere zaken gemeten. Gebeurt daar genoeg mee, of zijn bepaalde metingen overbodig?

Hoe zou je de kosten inschatten?

- Hoeveel proefvlakken per dag?
- Hoeveel mandagen
- Transportkosten
- Tijd op het proefvlak
    - Hoelang duurt kroonbeoordeling?
    - Hoelang duren de andere metingen?

### Vergelijking met buurlanden

- Zijn er gelijkaardige meetnetten?
- Indien zo, hoe zijn deze vergeleken met het INBO meetnet

## Wat willen we kunnen aantonen?

- Wat willen we detecteren? Welk effect over welke periode?
- Een bepaald percentage verschil over een periode van 12 jaar
- jaar tot jaar variatie
- inschatting algemeen over alle bomen heen
- inschatting per soort
- nog andere criteria?

## Welk model gebruiken we voor de analyse

- Gepaarde t-test (mixed effect model) voor de jaar-jaar variatie
- Sen slope over rollende 12 jaar?
- Toch een gewoon glm model ipv sen slope?

## Huidig steekproefdesign

- Hoeveel proefvlakken en hoe gekozen?
- Wat indien er een boom verdwijnt?
    - Hoe eventueel vervangen?
- Wat indien een proefvlak verdwijnt?
    - Hoe eventueel vervangen?

# Powerberekeningen

## Jaar tot jaar variatie

Normale benadering door centrale limietstelling: het gemiddelde van een mixture van metingen volgt vaak een normale distributie ongeacht de oorspronkelijke distributie

Rekening houden met paring van bomen genest in proefvlakken en boomsoort. Autocorrelatie is hier niet relevant omdat er maar 1 tijdstap is, en een mixed effect is dan per definitie ook de autocorrelatie

Dit uitvoeren algemeen over alle bomen, splitsing loof-naald, per hoofdboomsoort

- Inschatten variabiliteit tussen proefvlakken
- Inschatten variabiliteit binnen proefvlakken
- Inschatten variabiliteit tussen 2 jaren voor eenzelfde proefvlak
- Inschatten variabilitieit tussen 2 jaren voor eenzelfde boom

Power analyse

# Voorstellen voor meetnetaanpassingen
--->

<!--chapter:end:01_huidige_situatie.Rmd-->

---
# generic options. See ?INBOmd::report() for full list and more details.
title: Revisie Level I bosvitaliteitsmeetnet
author: 
  - firstname: "Pieter"
    name: "Verschelde"
    email: "pieter.verschelde@inbo.be"
    orcid: 0
  - firstname: "Geert"
    name: "Sioen"
    email: "geert.sioen@inbo.be"
    orcid: 0
style: INBO
lang: nl

# report specific options. See ?INBOmd::report() for full list and more details.
shortauthor: pieterverschelde
reviewer:
  - firstnaam: Firstname
    name: Lastname
    email: "firstname.lastname@inbo.be"
    orcid: 0
year: 2022
reportnr: 0
doi: 0
depotnr: 0
cover_description: none
output:
  INBOmd::gitbook: default
  INBOmd::report: default
  INBOmd::ebook: default
---

# Abstract

<!--chapter:end:Index.Rmd-->

```{r references, results = "asis", echo = FALSE}
# insert the references at this position
# set appendix = FALSE, when the report has no appendix
INBOmd::references(appendix = TRUE)
```

# Eerste hoofdstuk van de appendix

Inhoud van de eerste appendix

<!--chapter:end:zzz_references_and_appendix.Rmd-->

