# Aanbevelingen

## Doelstelling

De doelstelling van het meetnet moet concreet geformuleerd worden in meetbare termen. Een voorbeeld hiervan is een verschil kunnen detecteren van 12% in gemiddeld blad- en naaldverlies op een periode van 12 jaar.
Daarnaast kan er ook meer werk gemaakt worden van analyses waarbij de meetnetgegevens geconfronteerd worden met andere databronnen. Zo kan bijvoorbeeld de reactie van de bosvitaliteit op klimaatevoluties bekeken worden. Het publiceren van de bosvitaliteitsdata als open data verhoogt ook de kans dat de data voor zulke en andere actueel relevante vragen door de wetenschappelijke wereld worden gebruikt.

## Synergieën met andere meetnetten

Hoewel de bosvitaliteitsinventaris gestart is met een grid opgelegd door ICP-forests, en verdicht is door subgrids hiervan te gebruiken om voor het Vlaamse onderzoek meer informatie te verzamelen, is sedert 2012 gekozen om in synergie met de bosinventarisatie te werken met steekproefcirkels van 18 meter.
Nieuwe plots worden gekozen op basis van het raster van de bosinventaris.
Dus nieuwe bosvitaliteitsplots zijn steekproefpunten die ook door de bosinventaris bezocht worden.
In de toekomst zal gewerkt worden met een ruimtelijk gebalanceerd (grts) grid om nieuwe steekproefpunten te selecteren op het door ICP-forests gecreëerde 4 x 4 km grid.
Doorgaans zal het dichtsbijgelegen bosinventarisatiepunt genomen worden  als effectief meetpunt.

## Kostprijs meetnet

Indien gekozen wordt om een wijziging van 12% in blad- of naaldverlies te detecteren na 12 jaar lijkt de huidige steekproefopzet adequaat met ongeveer 80 plots met gemiddeld een 20-tal bomen per plot.

Indien echter een uitspraak op soortniveau gedaan moet worden zullen extra plots nodig zijn.


### Algemene kostprijs

Het meetnet is niet heel duur omdat de veldwerk inzet beperkt is in de huidige situatie tot ongeveer 40 mensdagen veldwerk, aangevuld met 90 dagen gegevensinvoer en kwaliteitsbewaking en de rapportage.

Er moet tijd voorzien worden voor het trainen van personeel om dit meetnet te kunnen verderzetten.

Qua veldwerk heeft het aantal plots de grootste impact op de kost en benodigde tijd.
Beperkingen van metingen binnen een plot kan iets helpen, maar veel minder.
Het nadeel is daarentegen dat het aantal plots ook de grootste invloedsfactor is voor het onderscheidend vermogen van het meetnet.
Dus er is een afweging noodzakelijk tussen kostprijs en gewenst onderscheidend vermogen.

Mogelijks zijn er ook winsten te halen door de rapportage iets beperkter te houden, aangezien het jaarlijkse rapport veel overlap heeft met rapporten uit de voorgaande jaren. Er is al veel tijdswinst geboekt doordat de meeste tabellen en figuren reeds via een R script automatisch aangemaakt worden.

Deels overlappend met dit meetnet en met dezelfde methodologie wordt ook de essenziekte onderzocht, maar het plan is dit heel binnenkort stop te zetten wegens de grote uitval door het aantal bomen dat sterft aan de gevolgen van de ziekte.
Dit neemt heel extreme proporties aan, waar in enkele jaren tijd reeds één derde van de bomen dood is.

## Technische verbeteringen voor de toekomst

### Representatitivteit

Om een goede uitspraak over Vlaanderen te doen, moeten we een goed zicht krijgen over hoe onze steekproef afwijkt (door stratificatie om sommige soorten meer mee te hebben) van de doelpopulatie in Vlaanderen.
Hiervoor kan bijvoorbeeld de bosinventarisatie gebruikt worden, al zal hier wel duidelijk gezorgd moeten worden dat bosrandplots niet meegeteld worden, omdat die niet voorkomen in de bosvitaliteit. Zo zal bijvoorbeeld de bosinventarisatie veel meer berk bevatten dan de steekproefpopulatie van het bosvitaliteitsmeetnet.


### Verouderende proefvlakken

Doordat het verouderen van de bomen zelf een steeds belangrijkere (maar nog steeds heel beperkte) factor  wordt in de evolutie van het bladverlies zelf, dekt dit meetnet niet meer volledig de doelstelling, daarom moet een goede vervangingstrategie worden uitgewerkt over hoelang proefvlakken in de dataset blijven en hoe die vervangen moeten worden, zodat de bosvitaliteit representatief blijft voor de gezondheidstoestand van de bomen in Vlaanderen.
Het is belangrijk om ook nieuwe aanplantingen mee te hebben in de steekproef.

### Trend over heel lange tijdreeks

Om de uitspraak zoals een gewoon meetnet te kunnen doen van een evolutie van 12% over 12 jaar wordt het meetnet eigenlijk een te lange tijdreeks met heel veel systematische subtrends en is het beter te focussen op de laatste 12 jaar in plaats van de hele tijdreeks te nemen voor de trend.

<!--hvc dit laatste kan je best nog iets anders formuleren. Het is mij bv niet duidelijk waarom je enkel naar de laatste 12 jaar zou kijken. Het lijkt mij ook relevant om de trend van de laatste 12 jaar te kunnen vergelijken met alle vorige resultaten van het rollende gemiddelde voor de rest van de tijdreeks. En misschien ook suggereren om naast lineaire trend op 12 jaar ook te kijken naar smoothing technieken om de tijdreeks te analyseren.-->
