---
# generic options. See ?INBOmd::pdf_report() for full list and more details.
title: Revisie bosvitaliteitsmeetnet 2022-2023
subtitle: Zoeken naar efficiëntie en effectiviteit 
author: 
  - name: 
      given: "Pieter"
      family: "Verschelde"
    email: "pieter.verschelde@inbo.be"
    affiliation: Research Institute for Nature and Forest (INBO)
    orcid: 0000-0002-9199-421X
    corresponding: true
style: INBO
lang: nl

# report specific options. See ?INBOmd::pdf_report() for full list and more details.
shortauthor: Verschelde P.
corresponding: pieter.verschelde@inbo.be
reviewer:
  - name: 
      given: "Hans"
      family: "Vancalster"
    email: "hans.vancalster@inbo.be"
    orcid: 0000-0001-8595-8426
    affiliation: Research Institute for Nature and Forest (INBO)
year: 2023
cover_photo: data/coverphoto.jpg
cover_description: Kronen die beoordeeld worden in een proefvlak
#doi: 00.00000/inbor.dummydoi
doi: 0.0/0.0
reportnr: XXXXXXXXX
depotnr: XXXXXXXXX
funder: Research Institute for Nature and Forest (INBO)
rightsholder: Research Institute for Nature and Forest (INBO)
community: inbo
keywords: tree; tree crown; vitality; leaf loss
floatbarrier: "section"
#client:
#  - Organisation (remove client section when not needed)
#  - Street number
#  - Postal code city
#  - https://www.website.com
# client_logo: uncomment and replace with path to logo or remove line
#cooperation:
#  - Organisation (remove cooperation section when not needed)
#  - Street number
#  - Postal code city
#  - https://www.website.com
# cooperation_logo: uncomment and replace with path to logo or remove line

# pdf report specific options. See ?INBOmd::pdf_report() for full list and more details.
embargo: 2023-06-19
#print:
#  copies: 0
#  motivation:
#  pages:

bibliography: references.bib
link-citations: TRUE
site: bookdown::bookdown_site
nocolophon: true

output:
  INBOmd::gitbook: default
  INBOmd::pdf_report: default
  #INBOmd::epub_book: default
  # Don't run the format below.
  # Only required for RStudio to recognise the project as a bookdown project.
  # Hence don't use "Build all formats".
  #bookdown::dontrun: default
---

# Dankwoord {-}

Bedankt aan Geert Sioen om me mee te nemen op een veldmeting en de nodige informatie te verschaffen om dit document te kunnen maken. 
Ook dank aan Hans Van Calster om de tekst na te lezen.

<!--
# Voorwoord {-}

De tekst voor het optionele voorwoord.
-->

# Samenvatting {-}

Dit rapport brengt het bosvitaliteitsmeetnet in kaart en onderzoekt of het meetnet goed gedimensioneerd is voor de vragen die het wil beantwoorden.

Het bosvitaliteitsmeetnet is een langlopend meetnet waarbij de vitaliteit van bomen wordt beoordeeld door een visuele inschatting van het percentage bladverlies in stappen van 5%.

Dit rapport zoekt eerst de sterke en zwakke punten van het meetnet op basis van de leidraad voor meetnetontwerp.
Daarna worden powerberekeningen uitgevoerd op een lineaire trendmodel om te bepalen welke effecten gedetecteerd kunnen worden met de huidige steekproef en wat de impact zou zijn bij wijzigingen in de steekproefdimensies.
Tot slot worden enkele aanbevelingen voor verbetering van het meetnet gedaan.

Uit de huidige analyse blijkt dat het meetnet, ondanks enkele tekortkomingen, goed gedimensioneerd is om een effect van 12% verandering in bladverlies te kunnen detecteren over een periode van 12 jaar wanneer we alle soorten samen beschouwen.

Het is echter belangrijk om geleidelijk aan steekproefpunten te vervangen door andere punten die samenvallen met punten in de Vlaamse bosinventarisatie, aangezien de huidige steekproefpunten verouderd raken en niet meer representatief zijn voor Vlaanderen.
Omdat we een analyse uitvoeren over alle soorten heen, is het van belang dat deze niet te veel afwijken van de soortendistributie in Vlaanderen voor steekproefpunten die volledig in het bos liggen.

<!--
De tekst voor de verplichte samenvatting.
Hou het [Heerlijk Helder](https://overheid.vlaanderen.be/communicatie/heerlijk-helder).


\benglish

# English abstract {-}

Insert a translation of the summary here.
\eenglish

\bfrench

# Résumé français {- #resume-francais}

Ajoutez éventuellement une traduction du résumé ici.

\efrench
-->

<!-- hier komt de inhoudstafel bij pdf -->
\mainmatter

```{r setup, include = FALSE}
library(knitr)
opts_chunk$set(
  echo = FALSE,
  eval = TRUE,
  cache = FALSE,
  warning = TRUE,
  error = FALSE,
  message = FALSE
)
library(tidyverse)
library(INBOtheme)
conflicted::conflicts_prefer(dplyr::filter)


if (interactive()) {
  theme_set(theme_inbo(base_size = 10))
} else {
  switch(
    opts_knit$get("rmarkdown.pandoc.to"),
    html = {
      opts_chunk$set(dev = "png", dpi = 72)
      theme_set(theme_inbo(base_size = 12))
    },
    latex = {
      opts_chunk$set(dev = "cairo_pdf", dpi = 300)
      theme_set(theme_inbo(base_size = 9))
      update_geom_defaults("point", list(size = 1.5))
    },
    epub3 = {
      opts_chunk$set(dev = "png", dpi = 300)
      theme_set(theme_inbo(base_size = 12))
    }
  )
}
```
